name: flutter_barcode_scanner
description: A plugin for barcode scanning support on Android and iOS. Supports barcodes, QR codes, etc.
version: 2.0.1  
homepage: https://github.com/AmolGangadhare/flutter_barcode_scanner
repository: https://github.com/AmolGangadhare/flutter_barcode_scanner
issue_tracker: https://github.com/AmolGangadhare/flutter_barcode_scanner/issues

environment:
  sdk: '>=3.0.0 <4.0.0'  
  flutter: ">=3.19.0"   

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.21  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  
  test: ^1.24.0         

flutter:
  plugin:
    platforms:
      android:
        package: com.amolg.flutterbarcodescanner
        pluginClass: FlutterBarcodeScannerPlugin
      ios:
        pluginClass: SwiftFlutterBarcodeScannerPlugin